### ISSUE TITLE
Should this module be split into two?

### ISSUE THREAD

**Issue by fent** [fent/node-muk#11]
Thinking of separating this module into two, one for its require mocking, and the other for the property mocking. Although they are both mocking utilities, they do so differently.

I'm considering this for mostly to keep things more organized, it's easier to think of tiny things, rather than maintaining a collection of functions.

If this were to be done, I'd be more in favor of moving property mocking into another module, and keeping this one with only require mocking. [The way require mocking works](https://github.com/fent/node-muk/blob/master/lib/index.js#L32-L35) makes it a bit complicated to include both in a collection-of-mocking-utilities library that depends on modules for each of the utilities.

Thoughts?

**Comment by alsotang** [comment]
@fengmk2

**Comment by fent** [comment]
I see. Another option is to create two additional repos and npm packages, and keep this one around. But with a note on the readme that says it's been abandoned and linking to the two new repos.

**Comment by alsotang** [comment]
two additional repos is a good idea

**Comment by fent** [comment]
Alright, repos created. I copied the `.git` dir to keep commit history. And added @popomore as a collaborator and npm owner.

* [muk-prop](https://github.com/fent/muk-prop.js) - Mock object methods and properties
* [muk-require](https://github.com/fent/node-muk-require) - Mock dependencies

**Comment by popomore** [comment]
So, we will maintain this two repo, and deprecate murk, isn't it?

**Comment by fent** [comment]
Correct
